name: Build test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - LICENSE
      - compile_flags.txt
      - .clang-format
      - .gitignore
  pull_request:
    paths-ignore:
      - "*.md"
      - LICENSE
      - compile_flags.txt
      - .clang-format
      - .gitignore

permissions:
  contents: read

jobs:
  build-test:
    name: On ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - name: Show environment
        run: |
          uname -a
          if type g++ > /dev/null; then
            g++ --version
          fi
          if type clang++ > /dev/null; then
            clang++ --version
          fi
      - run: make
      - uses: denoland/setup-deno@v2
      - name: Run tests
        run: |
          deno --version
          make test

  build-test-with-nix:
    name: On ${{ matrix.os }} with Nix
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - run: nix build .
      - uses: denoland/setup-deno@v2
      - name: Run tests
        run: |
          deno --version
          CHECK_TRUECOLOR_EXECUTABLE="$(pwd)/result/bin/check-truecolor" make test
