name: Build test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - LICENSE
      - compile_flags.txt
      - .clang-format
      - .gitignore
  pull_request:
    paths-ignore:
      - "*.md"
      - LICENSE
      - compile_flags.txt
      - .clang-format
      - .gitignore

permissions:
  contents: read

jobs:
  build-test:
    name: On ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Show environment
        run: |
          uname -a
          if type g++ > /dev/null; then
            g++ --version
          fi
          if type clang++ > /dev/null; then
            clang++ --version
          fi
      - run: make
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
      - name: Run tests
        run: |
          deno --version
          make test

  build-test-with-nix:
    name: On ${{ matrix.os }} with Nix
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      - run: nix build .
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
      - name: Run tests
        run: |
          deno --version
          CHECK_TRUECOLOR_EXECUTABLE="$(pwd)/result/bin/check-truecolor" make test
